name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t bharat1024/nodejs-app --build-arg EMAIL_USER='${{ secrets.EMAIL_USER }}' --build-arg EMAIL_PASS='${{ secrets.EMAIL_PASS }}' --build-arg PORT='${{ secrets.PORT }}' --build-arg SECRET_KEY='${{ secrets.SECRET_KEY }}' --build-arg RAZOR_KEY_ID='${{ secrets.RAZOR_KEY_ID }}' --build-arg RAZORPAY_SECRET='${{ secrets.RAZORPAY_SECRET }}'  .
      - name: Publish Image to docker hub
        run: docker push bharat1024/nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull bharat1024/nodejs-app:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container
      - name: Run Docker Container
        run: docker run -d -p 443:443 --name nodejs-app-container -e MONGO_URL='${{ secrets.MONGO_URL }}' bharat1024/nodejs-app
